# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_odds', '0003_timeofrefreshwilliamhill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeOfRefreshWilliamHill',
            new_name='TimeOfRefreshWilliamHill0',
        ),
    ]
