# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_odds', '0008_timeofrefreshwilliamhill2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOfRefreshWilliamHill3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_refresh', models.CharField(max_length=100)),
                ('william_hill_id', models.CharField(max_length=100)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
