# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_odds', '0014_auto_20170929_0930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WilliamHillUrlLink6',
        ),
    ]
