# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_odds', '0015_delete_williamhillurllink6'),
    ]

    operations = [
        migrations.CreateModel(
            name='WilliamHillGames0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.CharField(max_length=100)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('url_game_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillUrlLinks')),
            ],
        ),
        migrations.CreateModel(
            name='WilliamHillGames1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.CharField(max_length=100)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('url_game_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillUrlLinks')),
            ],
        ),
        migrations.CreateModel(
            name='WilliamHillGames2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.CharField(max_length=100)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('url_game_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillUrlLinks')),
            ],
        ),
        migrations.CreateModel(
            name='WilliamHillGames3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.CharField(max_length=100)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('url_game_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillUrlLinks')),
            ],
        ),
        migrations.CreateModel(
            name='WilliamHillGames4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.CharField(max_length=100)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('url_game_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillUrlLinks')),
            ],
        ),
        migrations.CreateModel(
            name='WilliamHillGames5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.CharField(max_length=100)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('url_game_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillUrlLinks')),
            ],
        ),
        migrations.CreateModel(
            name='WilliamHillGames6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.CharField(max_length=100)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('url_game_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillUrlLinks')),
            ],
        ),
        migrations.DeleteModel(
            name='GameUrlLink6',
        ),
        migrations.RemoveField(
            model_name='oddsgameurllink0',
            name='games',
        ),
        migrations.RemoveField(
            model_name='oddsgameurllink1',
            name='games',
        ),
        migrations.RemoveField(
            model_name='oddsgameurllink2',
            name='games',
        ),
        migrations.RemoveField(
            model_name='oddsgameurllink3',
            name='games',
        ),
        migrations.RemoveField(
            model_name='oddsgameurllink4',
            name='games',
        ),
        migrations.RemoveField(
            model_name='oddsgameurllink5',
            name='games',
        ),
        migrations.RemoveField(
            model_name='oddsgameurllink6',
            name='games',
        ),
        migrations.DeleteModel(
            name='GameUrlLink0',
        ),
        migrations.DeleteModel(
            name='GameUrlLink1',
        ),
        migrations.DeleteModel(
            name='GameUrlLink2',
        ),
        migrations.DeleteModel(
            name='GameUrlLink3',
        ),
        migrations.DeleteModel(
            name='GameUrlLink4',
        ),
        migrations.DeleteModel(
            name='GameUrlLink5',
        ),
        migrations.DeleteModel(
            name='OddsGameUrlLink0',
        ),
        migrations.DeleteModel(
            name='OddsGameUrlLink1',
        ),
        migrations.DeleteModel(
            name='OddsGameUrlLink2',
        ),
        migrations.DeleteModel(
            name='OddsGameUrlLink3',
        ),
        migrations.DeleteModel(
            name='OddsGameUrlLink4',
        ),
        migrations.DeleteModel(
            name='OddsGameUrlLink5',
        ),
        migrations.DeleteModel(
            name='OddsGameUrlLink6',
        ),
    ]
