# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_odds', '0016_auto_20170929_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='WilliamHillOdds0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('draw_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('away_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillUrlLinks')),
            ],
        ),
        migrations.CreateModel(
            name='WilliamHillOdds1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('draw_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('away_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillUrlLinks')),
            ],
        ),
        migrations.CreateModel(
            name='WilliamHillOdds2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('draw_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('away_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillUrlLinks')),
            ],
        ),
        migrations.CreateModel(
            name='WilliamHillOdds3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('draw_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('away_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillUrlLinks')),
            ],
        ),
        migrations.CreateModel(
            name='WilliamHillOdds4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('draw_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('away_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillUrlLinks')),
            ],
        ),
        migrations.CreateModel(
            name='WilliamHillOdds5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('draw_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('away_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillUrlLinks')),
            ],
        ),
        migrations.CreateModel(
            name='WilliamHillOdds6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('draw_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('away_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillUrlLinks')),
            ],
        ),
    ]
