# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games_odds', '0017_williamhillodds0_williamhillodds1_williamhillodds2_williamhillodds3_williamhillodds4_williamhillodds'),
    ]

    operations = [
        migrations.AddField(
            model_name='williamhillurllinks',
            name='url_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
