# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_odds', '0019_auto_20170929_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='williamhillgames0',
            name='games',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='williamhillgames1',
            name='games',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='williamhillgames2',
            name='games',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='williamhillgames3',
            name='games',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='williamhillgames4',
            name='games',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='williamhillgames5',
            name='games',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='williamhillgames6',
            name='games',
            field=models.CharField(max_length=300),
        ),
    ]
