# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_odds', '0021_auto_20171009_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='williamhillodds1',
            name='games',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillGames1'),
        ),
    ]
