# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_odds', '0022_auto_20171009_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='williamhillodds2',
            name='games',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillGames2'),
        ),
        migrations.AlterField(
            model_name='williamhillodds3',
            name='games',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillGames3'),
        ),
        migrations.AlterField(
            model_name='williamhillodds4',
            name='games',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillGames4'),
        ),
        migrations.AlterField(
            model_name='williamhillodds5',
            name='games',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillGames5'),
        ),
        migrations.AlterField(
            model_name='williamhillodds6',
            name='games',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillGames6'),
        ),
    ]
