# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_odds', '0023_auto_20171009_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='williamhillgames1',
            name='url_game_link',
        ),
        migrations.RemoveField(
            model_name='williamhillodds1',
            name='games',
        ),
        migrations.DeleteModel(
            name='WilliamHillGames1',
        ),
        migrations.DeleteModel(
            name='WilliamHillOdds1',
        ),
    ]
