# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_odds', '0024_auto_20171011_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='WilliamHillGames1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.CharField(max_length=300)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('url_game_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillCsvLinks')),
            ],
        ),
        migrations.CreateModel(
            name='WilliamHillOdds1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('draw_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('away_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillGames1')),
            ],
        ),
    ]
