# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_odds', '0026_coralcsvlinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoralCsvLinks',
            new_name='CoralCsvWebLinks',
        ),
    ]
