# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_odds', '0027_auto_20171213_0814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoralCsvWebLinks',
            new_name='CoralCsvLinks',
        ),
    ]
