# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_odds', '0028_auto_20171213_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coralcsvlinks',
            name='get_match_odds_link_csv',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coralcsvlinks',
            name='ids_for_tag_span_link_csv',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coralcsvlinks',
            name='ids_for_tag_tbody_link_csv',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coralcsvlinks',
            name='url_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
