# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_odds', '0029_auto_20171216_1026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoralCsvLinks',
        ),
    ]
