# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_odds', '0030_delete_coralcsvlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoralGames0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.CharField(max_length=300)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('match_day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.WilliamHillCsvLinks')),
            ],
        ),
    ]
