# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_odds', '0031_coralgames0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coralgames0',
            name='match_day_id',
        ),
        migrations.DeleteModel(
            name='CoralGames0',
        ),
    ]
