# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.CharField(max_length=50)),
                ('time', models.TimeField(blank=True, verbose_name='Time of Game')),
                ('date_of_game', models.DateField(blank=True, verbose_name='Date of Game')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
