# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accumulator.Game')),
            ],
        ),
    ]
