# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0003_odds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Odds',
            new_name='Odd',
        ),
    ]
