# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0004_auto_20170227_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='games',
        ),
        migrations.DeleteModel(
            name='Bet',
        ),
    ]
