# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0005_auto_20170227_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_matches', models.CharField(max_length=200)),
                ('combinations', models.CharField(max_length=200)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
