# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0006_dailymatches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyMatches',
            new_name='DailyMatche',
        ),
    ]
