# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0006_matchinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_of_game',
            field=models.DateField(null=True, verbose_name='Date of Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(null=True, verbose_name='Time of Game'),
        ),
    ]
