# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0007_auto_20170418_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookies_name', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookiesUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookies_url_name', models.CharField(max_length=50)),
                ('bookies_urls', models.CharField(max_length=200)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('bookies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accumulator.Bookies')),
            ],
        ),
    ]
