# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0008_bookies_bookiesurls'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookies',
            new_name='Bookie',
        ),
        migrations.RenameModel(
            old_name='BookiesUrls',
            new_name='BookiesUrl',
        ),
    ]
