# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0009_auto_20171010_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookiesurl',
            name='bookies_id',
        ),
        migrations.DeleteModel(
            name='BookiesUrl',
        ),
    ]
