# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0011_bookiesdailymatche'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookiesdailymatche',
            old_name='bookies_id',
            new_name='bookies',
        ),
    ]
