# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0012_auto_20171011_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookiesDailyMatche',
            new_name='WilliamHillDailyMatche',
        ),
    ]
