# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0020_williamhilldailymatche_wh_csv_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='williamhilldailymatche',
            name='wh_csv_links',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accumulator.Game'),
        ),
    ]
