# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0023_auto_20171016_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='WilliamHillGamesWithOdds0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=200)),
                ('home_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('draw_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('away_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
