# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0025_williamhillgameswithodds0_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='williamhillgameswithodds0',
            name='games',
            field=models.IntegerField(default=0),
        ),
    ]
