# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0026_auto_20171104_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='williamhillgameswithodds0',
            old_name='games',
            new_name='games_id',
        ),
    ]
