# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0027_auto_20171104_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoralDailyMatche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates_of_games', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('bookies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accumulator.Bookie')),
            ],
        ),
    ]
