# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-07 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0028_coraldailymatche'),
    ]

    operations = [
        migrations.AddField(
            model_name='coraldailymatche',
            name='dates_id',
            field=models.IntegerField(default=0),
        ),
    ]
