# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0028_coraldailymatche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coraldailymatche',
            name='coral_csv_links',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_odds.CoralCsvLinks'),
        ),
    ]
