# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0031_coralodds0'),
    ]

    operations = [
        migrations.AddField(
            model_name='coralodds0',
            name='match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accumulator.CoralGames0'),
        ),
    ]
