# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accumulator', '0032_coralodds0_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoralGames1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.CharField(max_length=300)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('match_day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accumulator.CoralDailyMatche')),
            ],
        ),
        migrations.CreateModel(
            name='CoralOdds1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('draw_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('away_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accumulator.CoralDailyMatche')),
                ('match', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accumulator.CoralGames1')),
            ],
        ),
    ]
