from django.contrib import admin
from games_odds.models import TimeOfRefreshWilliamHill0, TimeOfRefreshWilliamHill1, TimeOfRefreshWilliamHill2, TimeOfRefreshWilliamHill3, TimeOfRefreshWilliamHill4, TimeOfRefreshWilliamHill5, TimeOfRefreshWilliamHill6, WilliamHillCsvLinks, WilliamHillGames0, WilliamHillGames1, WilliamHillGames2, WilliamHillGames3, WilliamHillGames4, WilliamHillGames5, WilliamHillGames6, WilliamHillOdds0, WilliamHillOdds1, WilliamHillOdds2, WilliamHillOdds3, WilliamHillOdds4, WilliamHillOdds5, WilliamHillOdds6

admin.site.register(TimeOfRefreshWilliamHill0)
admin.site.register(TimeOfRefreshWilliamHill1)
admin.site.register(TimeOfRefreshWilliamHill2)
admin.site.register(TimeOfRefreshWilliamHill3)
admin.site.register(TimeOfRefreshWilliamHill4)
admin.site.register(TimeOfRefreshWilliamHill5)
admin.site.register(TimeOfRefreshWilliamHill6)
admin.site.register(WilliamHillCsvLinks)
admin.site.register(WilliamHillGames0)
admin.site.register(WilliamHillGames1)
admin.site.register(WilliamHillGames2)
admin.site.register(WilliamHillGames3)
admin.site.register(WilliamHillGames4)
admin.site.register(WilliamHillGames5)
admin.site.register(WilliamHillGames6)
admin.site.register(WilliamHillOdds0)
admin.site.register(WilliamHillOdds1)
admin.site.register(WilliamHillOdds2)
admin.site.register(WilliamHillOdds3)
admin.site.register(WilliamHillOdds4)
admin.site.register(WilliamHillOdds5)
admin.site.register(WilliamHillOdds6)
